"""first migrate

Revision ID: 3d20fa81aafb
Revises: 
Create Date: 2023-03-28 11:28:53.512734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d20fa81aafb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enregistrement_av')
    with op.batch_alter_table('apporter_analyse', schema=None) as batch_op:
        batch_op.drop_index('identifiant')

    op.drop_table('apporter_analyse')
    with op.batch_alter_table('action_programme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('libelle_action', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('commentaire', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('pourquoi5_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'pourquoi5', ['pourquoi5_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('action')

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index('name')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plateau_id', sa.Integer(), nullable=True))
        batch_op.drop_index('plateau')
        batch_op.drop_index('profil')
        batch_op.create_foreign_key(None, 'plateaux', ['plateau_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('plateau')

    with op.batch_alter_table('valeurs_aberrante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('probleme', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('valeurs_aberrante', schema=None) as batch_op:
        batch_op.drop_column('probleme')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plateau', mysql.VARCHAR(length=150), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('profil', ['profil'], unique=False)
        batch_op.create_index('plateau', ['plateau'], unique=False)
        batch_op.drop_column('plateau_id')

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=False)

    with op.batch_alter_table('action_programme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pourquoi5_id')
        batch_op.drop_column('commentaire')
        batch_op.drop_column('libelle_action')

    op.create_table('apporter_analyse',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('identifiant', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('famille_causes', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('probleme', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('pourquoi_1', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('pourquoi_2', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('pourquoi_3', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('pourquoi_4', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('pourquoi_5', mysql.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('apporter_analyse', schema=None) as batch_op:
        batch_op.create_index('identifiant', ['identifiant'], unique=False)

    op.create_table('enregistrement_av',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('agent', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('reference_av', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('libelle_av', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('statut_analyse', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('commentaire', mysql.VARCHAR(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
