"""changement attribut action en libelle_action de la table ActionProgramme

Revision ID: 87ed49c58364
Revises: ee9d452c3a78
Create Date: 2023-03-25 22:18:09.841732

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '87ed49c58364'
down_revision = 'ee9d452c3a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_programme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('libelle_action', sa.String(length=255), nullable=True))
        batch_op.drop_column('action')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_programme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('libelle_action')

    # ### end Alembic commands ###
