"""enlevement table AnalyseApporter et Enregistrement_AV

Revision ID: c33d04934b42
Revises: f2e9fae81c37
Create Date: 2023-03-15 23:21:46.522888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c33d04934b42'
down_revision = 'f2e9fae81c37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enregistrement_av')
    with op.batch_alter_table('apporter_analyse', schema=None) as batch_op:
        batch_op.drop_index('identifiant')

    op.drop_table('apporter_analyse')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apporter_analyse',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('identifiant', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('famille_causes', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('probleme', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('pourquoi_1', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('pourquoi_2', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('pourquoi_3', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('pourquoi_4', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('pourquoi_5', mysql.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('apporter_analyse', schema=None) as batch_op:
        batch_op.create_index('identifiant', ['identifiant'], unique=False)

    op.create_table('enregistrement_av',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('agent', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('reference_av', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('libelle_av', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('statut_analyse', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('commentaire', mysql.VARCHAR(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
