"""modification de l'attribut profil de User a unique=False

Revision ID: d86f76e2eb1f
Revises: c33d04934b42
Create Date: 2023-03-15 23:33:42.141621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd86f76e2eb1f'
down_revision = 'c33d04934b42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('profil')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('profil', ['profil'], unique=False)

    # ### end Alembic commands ###
