"""changement type de lattribut valeur en float pour la table ValeurFichier

Revision ID: f1eac99de9c7
Revises: 700fb698cb2f
Create Date: 2023-04-11 10:50:17.206977

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1eac99de9c7'
down_revision = '700fb698cb2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('valeurs_fichier', schema=None) as batch_op:
        batch_op.alter_column('valeur',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('valeurs_fichier', schema=None) as batch_op:
        batch_op.alter_column('valeur',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
