"""Initial migration.

Revision ID: f2e9fae81c37
Revises: 
Create Date: 2023-03-13 07:53:41.666545

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2e9fae81c37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_programme', schema=None) as batch_op:
        batch_op.drop_constraint('action_programme_ibfk_1', type_='foreignkey')
        batch_op.drop_column('pourquoi5_id')

    with op.batch_alter_table('statut', schema=None) as batch_op:
        batch_op.add_column(sa.Column('libelle', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=80), nullable=True))
        batch_op.drop_column('cloture')
        batch_op.drop_column('valide')
        batch_op.drop_column('enregistre')

    with op.batch_alter_table('valeurs_aberrante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('probleme', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('valeurs_aberrante', schema=None) as batch_op:
        batch_op.drop_column('probleme')

    with op.batch_alter_table('statut', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enregistre', mysql.VARCHAR(length=80), nullable=True))
        batch_op.add_column(sa.Column('valide', mysql.VARCHAR(length=80), nullable=True))
        batch_op.add_column(sa.Column('cloture', mysql.VARCHAR(length=80), nullable=True))
        batch_op.drop_column('description')
        batch_op.drop_column('libelle')

    with op.batch_alter_table('action_programme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pourquoi5_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('action_programme_ibfk_1', 'pourquoi5', ['pourquoi5_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
