"""modification de l'attribut name de role a unique=False

Revision ID: fd31d24fa0bf
Revises: d86f76e2eb1f
Create Date: 2023-03-15 23:40:22.326871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd31d24fa0bf'
down_revision = 'd86f76e2eb1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=False)

    # ### end Alembic commands ###
